# Generated by Django 2.1.4 on 2019-11-19 22:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('info', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('artists', models.ManyToManyField(to='artists.Artist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
