# Generated by Django 2.2.4 on 2019-11-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Residencies'},
        ),
    ]
