# Generated by Django 2.1.4 on 2019-11-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_residencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='residencies',
        ),
    ]
